---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ellecube
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: ellecube
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
