---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ellecube
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:365551658960:certificate/9b138db9-dd94-4bcb-90d8-16c402ba0114
    # external-dns.alpha.kubernetes.io/alias: true # if set to true on an ingress, it will create an ALIAS record when the target is an ALIAS as well.
    # alb.ingress.kubernetes.io/subnets: subnet-000000,subnet-111111,subnet-22222
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # alb.ingress.kubernetes.io/target-type: ip
    # kubernetes.io/ingress.global-static-ip-name: ellecube-lb
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: ellecafe.jp
    http:
      paths:
      - backend:
          serviceName: ellecube
          servicePort: 80
      # - backend:
          # serviceName: ssl-redirect
          # servicePort: use-annotation
  # tls:
  # - secretName: ellecube-tls
