#!/bin/bash

vault=`which ansible-vault`
secret=secret/vault-password.txt

if [ ! -f $secret ]; then
    read -sp "Password: " PASS
    mkdir -p secret && echo $PASS > $secret
fi

gcpkey=`$vault view .gcpkey.json.vault --vault-password-file=$secret | cat -`
cubefpm=`$vault view .fastcgi_params_secret.cubefpm.vault --vault-password-file=$secret | cat -`
environ=`$vault view .env.vault --vault-password-file=$secret | cat -`

mkdir -p ./overlays/production/elle/secret
echo  $gcpkey   > ./overlays/production/elle/secret/elle-gcpkey.json
echo "$cubefpm" > ./overlays/production/elle/secret/fastcgi_params_secret.cubefpm
echo "$environ" > ./overlays/production/elle/secret/elle.env
