#!/bin/bash

vault=`which ansible-vault`
SECRET=secret/vault-password.txt

if [ ! -f $SECRET ]; then
    read -sp "Password: " PASS
    mkdir -p secret && echo $PASS > $SECRET
fi

GCPKEY=`$vault view .gcpkey.json.vault --vault-password-file=$SECRET | cat -`

mkdir -p ./overlays/production/elle/secret
echo $GCPKEY > ./overlays/production/elle/secret/elle-gcpkey.json

$vault view .env.vault --vault-password-file=$SECRET | cat -

